Update some front-end components
eoscostarica/eos-rate pull request #681
Opened 2021-08-13 22:17 UTC by AngeloCG97

## Add padlock icon on navbar
##Change messages info component
##Align pils conten 

Resolve #677
Resolve #678
Resolve #680

### What does this PR have?

1. Change messages component by snackbar
1. Add messages on volting tool component
1. Add padlook component to navbar
2. Align pils content

2021-08-13 22:48 UTC, xavier506 requested changes

2021-08-13 22:48 UTC, xavier506 commented on webapp/src/components/app-bar/index.js
> +  const [mayVoting, setMayVoting] = useState(false)
mayVote not mayVoting

2021-08-13 22:48 UTC, xavier506 commented on webapp/src/language/en.json
> +    "unlockedRating": "User is a voter. Ratings unlocked",
You must vote for at least 21 block producers or a proxy to unlock ratings

2021-08-13 22:48 UTC, xavier506 commented on webapp/src/language/en.json
> +    "unlockedRating": "User is a voter. Ratings unlocked",
You have voted for 21 bps or a proxy and have unlocked ratings

2021-08-16 05:17 UTC, leisterfrancisco requested changes

2021-08-16 05:17 UTC, leisterfrancisco commented on webapp/src/components/compare-tool/index.js
> +          Success!
Angelo we could add some I18N to avoid this hard coded text

2021-08-16 05:17 UTC, leisterfrancisco commented on webapp/src/routes/proxies/proxy-profile.js
> +                Success!
Same here

2021-08-16 16:24 UTC, leisterfrancisco approved these changes

2021-08-16 16:31 UTC, merged