feat(webapp): Add my rating on bp profile and rating page
eoscostarica/eos-rate pull request #868
Opened 2021-11-25 20:27 UTC by AngeloCG97

## Add my rating in bp profile and rating page

Resolve #867

2021-11-26 17:19 UTC, xavier506 approved these changes
LGTM

2021-12-03 13:08 UTC, tetogomez approved these changes
LGTM

2021-12-03 14:24 UTC, leisterfrancisco commented on hapi/src/libs/sync-stats.js
> +    if (!haveTowRating) {
haveTowRating -> haveTwoRating

2021-12-03 14:24 UTC, leisterfrancisco commented on hapi/src/libs/sync-stats.js
> +    if (!haveTowRating) {
leave space before

2021-12-03 14:26 UTC, leisterfrancisco requested changes

2021-12-03 14:26 UTC, leisterfrancisco commented on hapi/src/libs/sync-stats.js
> +    if (!haveTowRating) {
add space before

2021-12-03 15:01 UTC, leisterfrancisco requested changes

2021-12-03 15:01 UTC, leisterfrancisco commented on hapi/src/config/index.js
> +  edenContractScope: 'eden'
@AngeloCG97 there is a global variable for this, it is `edenContractScope`, try to use it

2021-12-03 15:09 UTC, leisterfrancisco approved these changes

2021-12-03 15:09 UTC, merged