Feat/bp page styles
eoscostarica/eos-rate pull request #895
Opened 2022-02-10 22:40 UTC by hanakoori01

### What does this PR do?

- Resolves #809 

### Steps to test

1. Run `make run`
2. Go to `localhost:3000`
3. Go to Block Producers > Block Producer Profile 

### Checklist
- [ ] I have added/updated tests to cover these changes.
- [ ] The branch name, commit history and PR title follow [conventions](https://developers.eoscostarica.io/docs/open-source-guidelines#pull-request-general-guidelines).
- [ ] I have taken into consideration any impact to site performance.

2022-02-11 17:29 UTC, AngeloCG97 reviewed
Please change

``` 
<TableBoxColor color={polarChartData[0].color}></TableBoxColor>
```
by 
``` 
<TableBoxColor color={polarChartData[0].color} />
```

2022-02-11 17:33 UTC, AngeloCG97 commented on webapp/src/components/TableBoxColor/index.js
> +      style={{ borderColor: LightenDarkenColor('#a43bca99', 80) }}
Please remove inline style and change by Box props

``` 
borderColor={ LightenDarkenColor('#a43bca99', 80) }
```

2022-02-14 17:24 UTC, tetogomez approved these changes
LGTM

2022-02-16 16:05 UTC, AngeloCG97 requested changes

2022-02-16 16:05 UTC, AngeloCG97 commented on webapp/src/routes/BlockProducers/BlockProducerProfile.js
> +            {console.log(polarChartData)}
Please remove this console.log

2022-02-16 16:35 UTC, AngeloCG97 requested changes

2022-02-16 17:29 UTC, AngeloCG97 approved these changes
LGTM

2022-02-16 17:29 UTC, merged